package khonraad.mps.tutorial.calculator.sandbox;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import javax.swing.JTextField;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

public class MySalaryCalculator extends JFrame {
  private DocumentListener listener = new DocumentListener() {
    @Override
    public void insertUpdate(DocumentEvent p0) {
      update();
    }

    @Override
    public void removeUpdate(DocumentEvent p0) {
      update();
    }

    @Override
    public void changedUpdate(DocumentEvent p0) {
      update();
    }
  };

  private JTextField inputField_3bq9f0_a = new JTextField();
  private JTextField inputField_3bq9f0_b = new JTextField();

  private JTextField outputField_3bq9f0_a = new JTextField();


  public MySalaryCalculator() {
    setTitle("MySalaryCalculator");
    setLayout(new GridLayout(0, 2));
    inputField_3bq9f0_a.getDocument().addDocumentListener(listener);
    add(new JLabel("Java Hours"));
    add(inputField_3bq9f0_a);
    inputField_3bq9f0_b.getDocument().addDocumentListener(listener);
    add(new JLabel("PHP Hours"));
    add(inputField_3bq9f0_b);

    add(new JLabel("my Pay" + " output"));
    add(outputField_3bq9f0_a);

    update();
    setDefaultCloseOperation(EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }

  public void update() {
    int i_a_0 = 0;
    int i_b_0 = 0;
    try {
      i_a_0 = Integer.parseInt(inputField_3bq9f0_a.getText());
      i_b_0 = Integer.parseInt(inputField_3bq9f0_b.getText());
    } catch (NumberFormatException e) {
    }

    outputField_3bq9f0_a.setText("" + (i_a_0 * 10 + i_b_0 * 6));
  }

  public static void main(String[] args) {
    SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        new MySalaryCalculator();
      }
    });
  }
}
